In [32]:
# Creating Tensros
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [33]:
# Crating a Vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [34]:
import tensorflow as tf
matrix = tf.constant([[10., 7.], 
                      [3., 2.],
                      [8., 9.]])
matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>